openapi: 3.0.0
info:
  title: 'Comment Api'
  description: 'This is the Comment API documentation.'
  version: 1.0.0
servers:
  -
    url: 'http://api.comment.com/v1'
    description: 'Local Server'
paths:
  /comments:
    get:
      tags:
        - comments-service
      summary: 'Get all comments'
      operationId: index
      responses:
        200:
          description: Success
          content:
            application/json: {  }
        400:
          description: 'Bad Request'
        401:
          description: Unauthorized
        500:
          description: 'Internal Server'
    post:
      tags:
        - comments-service
      summary: 'Add comment to the static post'
      operationId: store
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                body:
                  type: string
                comment_level:
                  type: integer
                reply_id:
                  type: integer
              type: object
      responses:
        200:
          description: Success
          content:
            application/json: {  }
        400:
          description: 'Bad Request'
        401:
          description: Unauthorized
        422:
          description: 'Unprocessable Entity'
        500:
          description: 'Internal Server'
components:
  schemas:
    Comment:
      properties:
        id:
          type: integer
        name:
          type: string
        body:
          type: string
        comment_level:
          type: integer
        reply_id:
          type: integer
      type: object
tags:
  -
    name: comments-service
    description: 'Comment Controller'
